# -*- coding: utf-8 -*-
"""03_Age of First Kiss_IQ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13aBH7fxN4XLpFrL7lVs_UnNC6Cjs6C8W
"""

# Import necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# Load the Excel file into a pandas DataFrame.
# 'header=0' indicates that the first row (row 0) contains the column names.
df = pd.read_excel('DATA_Kiss_count_gender_and_IQ.xlsx', header=0)


###### Divide IQ into 2 quantile-based groups (Low and High) ######
# Also return the bin edges to use for labeling the IQ ranges
df['IQ_Group'], bin_edges = pd.qcut(df['IQ'], q=2, labels=['Low', 'High'], retbins=True)

### Compute the Pearson correlation coefficient and p-value ######
# between IQ and Age of First Kiss
r_value, p_value = pearsonr(df['IQ'], df['Age of First Kiss'])

### Create a boxplot showing Age of First Kiss by IQ group ######
plt.figure(figsize=(8, 6))
sns.boxplot(
    x='IQ_Group',
    y='Age of First Kiss',
    data=df,
    hue='IQ_Group',               # Add hue to apply palette without warning
    palette='Pastel1'             # Soft colors for better visualization
)

# Add main title with correlation statistics
plt.title(
    f'Age of First Kiss by IQ Group\n'
    f'r = {r_value:.2f}, p = {p_value:.3f}'
)

# Set axis labels
plt.xlabel('IQ Group')
plt.ylabel('Age of First Kiss')

# Add gridlines for readability
plt.grid(True)

# Add text box indicating the actual IQ range of the two groups
plt.text(
    x=1.1,                                # x-position (just right of the plot)
    y=df['Age of First Kiss'].max() - 1.5, # y-position (slightly below max age)
    s=f'IQ Range:\nLow ≤ {bin_edges[1]:.1f}\nHigh > {bin_edges[1]:.1f}',
    fontsize=10,
    bbox=dict(facecolor='white', edgecolor='black')  # Add border and background to the text
)

# Ensure the layout does not overlap elements
plt.tight_layout()
plt.show()